trigger:
  - master
  - dev

pool:
  vmImage: ubuntu-latest

parameters:
  - name: resourceGroupPrefix
    displayName: Resource Group Prefix
    type: string
    default: fwlab
  - name: environment
    displayName: Environment
    default: sandbox
    type: string
    values:
      - prod
      - dev
      - sandbox
  - name: subscriptionID
    displayName: Subscription ID
    type: string
    default: 5af4ad96-ee54-40ce-9564-3a35874e68d9
  - name: azureServicePrincipal
    displayName: Azure Service Principal
    type: string
    default: gp-firewall-lab-2
  - name: location
    displayName: Azure Region
    type: string
    default: westus3
    values:
      - westus3
      - westus2
      - westus
  - name: deployfirewall
    displayName: Deploy Firewall toggle
    type: string
    default: true
    values:
      - true
      - false

stages:
- stage: prerequisites
  jobs:
    - job:  createResourceGroup
      steps:
        - task: AzureCLI@2
          inputs:
            connectedServiceNameARM: '${{ parameters.azureServicePrincipal }}'
            scriptType:  bash
            scriptLocation: inlineScript
            inlineScript:  az group create -l ${{ parameters.location }} -n ${{ parameters.resourceGroupPrefix }}-${{ parameters.environment }}-rg
            failOnStandardError:  true

        