parameters:
  - name: azureServicePrincipal
    displayName: Azure Service Principal
    type: string
    default: JohnTudong_vs_sandbox_20230426

pool:
  vmImage: ubuntu-latest

variables:
- group: firewall-vars-1                             # Group variables
                                                          #   deployFirwall
                                                          #   environment
                                                          #   location
                                                          #   parameterFile
                                                          #   subnetPrefix
                                                          #   templateFile
                                                          # Pipeline variables
                                                          #   adminPassword
                                                          #   bootstrapAccessKey
                                                          #
- name: varResourceGroupName
  value: sfc-$(subnetPrefix)-$(environment)-rg

#steps:
#- script: |
#    echo $(resources.pipeline.main.pipelineID)
#    echo $(resources.pipeline.main.runName)
#    echo $(resources.pipeline.main.runID)
#    echo $(resources.pipeline.main.runURI)
#    echo $(resources.pipeline.main.sourceBranch)
#    echo $(resources.pipeline.main.sourceCommit)
#    echo $(resources.pipeline.main.sourceProvider)
#    echo $(resources.pipeline.main.requestedFor)
#    echo $(resources.pipeline.main.requestedForID)
#    echo $(subnetPrefix)
#    echo $(location)
#    echo $(environment)
jobs:
  - job: createResourceGroup
    steps:
      - task: AzureCLI@2
        inputs:
          connectedServiceNameARM: ${{ parameters.azureServicePrincipal }}
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript:  az group create -l $(location) -n $(varResourceGroupName) --tags Application=network Team=networking Department=it Environment=$(environment)
          failOnStandardError:  true
